# See: https://github.com/DavidAnson/markdownlint

# Unordered list style
MD004:
  style: dash

# Reversed link syntax
MD011: false

# Disable line length for tables
MD013: false

# Ordered list item prefix
MD029:
  style: one

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Inline HTML
MD033:
  allowed_elements:
    - table
    - thead
    - tbody
    - tr
    - th
    - td
    - ul
    - li
    - code
    - a
    - b

# Code block style
MD046:
  style: fenced
